- type: job
  id: Reimu
  name: job-name-Reimu
  description: job-description-Reimu
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3600
    - !type:OverallPlaytimeRequirement
      time: 54000
  weight: 10
  startingGear: HoSGear
  icon: "YinYang"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  whitelistRequired: true
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - Detective
  - External
  special:
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance
      flatBonus: 0.025
    - type: BasicDanmaku

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
